// GENERATED by scripts/gen_game_data.py from game/data/*.tsv.
// Do not edit. Change the TSV and regenerate; CI runs --check.

pub const COLS: i32 = 72;
pub const ROWS: i32 = 36;

/// Odd-r offset grid, row-major. '#' is land, '.' is open water.
/// 1773 of 2592 cells are sea reachable from every port.
pub const LAND: &[u8] = b"\
........................................................................\
........................................................................\
......................##########........................................\
.......................#########...................############.........\
.....############.......#######.......####~#######~###################..\
....################......##.........##################################.\
.........#############.............#..~#....####################.~..#...\
..........#############...........#~~#~#....####################........\
...........############............###~#...~###################.........\
...........~##########............#~~~~#.~.~##################..........\
...........#########~.............~~~.~...###################...........\
............#########.............~#~#~#.~.##~.##############~..........\
.............####..#.............##########....~############............\
..............##~..##...........~##########~...~..~#######~~............\
....~#..........~#..~#~........#.##########..##...~##..##~..............\
.................~..~.~........~.###########.~....~~...##...#...~#......\
....................~###..........#~##########.....~#..~................\
....................#####.............#######...........~.##.~..........\
....................#######...........#####~............#.###~##........\
....................~########~........~####~.............~#...###~......\
.....................########.........######..................###.......\
.....................#######..........#####.~#..............~####.......\
.....................######~...........###~..#.............#######......\
.....................~####.............###.................########.....\
......................###~.............~##.................##.####......\
.....................###........................................##......\
.....................##.................................................\
.....................##.................................................\
......................#.................................................\
........................................................................\
........................................................................\
........................................................................\
...........................#############################################\
########################################################################\
########################################################################\
########################################################################\
";

pub struct Port {
    pub name: &'static str,
    pub col: i16,
    pub row: i16,
    /// Index into ECONOMIES, or -1 for a landfall that does not trade.
    pub econ: i8,
    /// Index into GOODS for the good this port is known for, or -1.
    pub specialty: i16,
    /// Has a shipyard. Only a capital sells ships; everywhere else you
    /// sail in with what you have. Never true of a port that does not trade.
    pub capital: bool,
}

pub const PORTS: [Port; 70] = [
    Port { name: "Acapulco", col: 16, row: 14, econ: -1, specialty: -1, capital: false },
    Port { name: "Aden", col: 45, row: 15, econ: 5, specialty: 12, capital: false },
    Port { name: "Alexandria", col: 41, row: 11, econ: 0, specialty: 16, capital: false },
    Port { name: "Algiers", col: 36, row: 11, econ: 0, specialty: -1, capital: false },
    Port { name: "Amboina", col: 61, row: 18, econ: 6, specialty: 2, capital: false },
    Port { name: "Antwerp", col: 36, row: 7, econ: 1, specialty: 7, capital: false },
    Port { name: "Argin", col: 32, row: 13, econ: 3, specialty: -1, capital: false },
    Port { name: "Azov", col: 43, row: 8, econ: 1, specialty: -1, capital: false },
    Port { name: "Baghdad", col: 45, row: 11, econ: 5, specialty: 24, capital: false },
    Port { name: "Bordeaux", col: 35, row: 9, econ: 1, specialty: 6, capital: false },
    Port { name: "Calicut", col: 51, row: 15, econ: 6, specialty: 0, capital: false },
    Port { name: "Cape Town", col: 39, row: 24, econ: -1, specialty: -1, capital: false },
    Port { name: "Caracas", col: 22, row: 15, econ: 2, specialty: -1, capital: false },
    Port { name: "Ceylon", col: 51, row: 16, econ: 6, specialty: 1, capital: false },
    Port { name: "Chanchan", col: 20, row: 19, econ: -1, specialty: -1, capital: false },
    Port { name: "Cochin", col: 50, row: 15, econ: 6, specialty: -1, capital: false },
    Port { name: "Copiapo", col: 21, row: 23, econ: -1, specialty: -1, capital: false },
    Port { name: "Da Nang", col: 57, row: 14, econ: -1, specialty: -1, capital: false },
    Port { name: "Diu", col: 50, row: 13, econ: 5, specialty: -1, capital: false },
    Port { name: "Eureka", col: 11, row: 9, econ: -1, specialty: -1, capital: false },
    Port { name: "Genoa", col: 37, row: 9, econ: 0, specialty: -1, capital: false },
    Port { name: "Goa", col: 50, row: 14, econ: 6, specialty: 19, capital: false },
    Port { name: "Guam", col: 64, row: 15, econ: -1, specialty: -1, capital: false },
    Port { name: "Guatemala", col: 17, row: 15, econ: 2, specialty: -1, capital: false },
    Port { name: "Hamburg", col: 38, row: 7, econ: 1, specialty: 18, capital: false },
    Port { name: "Hormuz", col: 47, row: 12, econ: 5, specialty: 3, capital: true },
    Port { name: "Injiga", col: 42, row: 4, econ: -1, specialty: -1, capital: false },
    Port { name: "Istanbul", col: 41, row: 9, econ: 0, specialty: 24, capital: false },
    Port { name: "Jamaica", col: 20, row: 14, econ: 2, specialty: -1, capital: false },
    Port { name: "Java", col: 57, row: 19, econ: 6, specialty: 0, capital: false },
    Port { name: "Kailua", col: 4, row: 14, econ: -1, specialty: -1, capital: false },
    Port { name: "Leveque", col: 60, row: 21, econ: -1, specialty: -1, capital: false },
    Port { name: "Lisbon", col: 34, row: 10, econ: 0, specialty: 7, capital: true },
    Port { name: "London", col: 35, row: 7, econ: 1, specialty: 18, capital: true },
    Port { name: "Luanda", col: 38, row: 19, econ: -1, specialty: -1, capital: false },
    Port { name: "Macao", col: 58, row: 13, econ: 7, specialty: -1, capital: false },
    Port { name: "Madang", col: 65, row: 19, econ: -1, specialty: -1, capital: false },
    Port { name: "Majorca", col: 36, row: 10, econ: 0, specialty: 9, capital: false },
    Port { name: "Malacca", col: 56, row: 17, econ: 6, specialty: 0, capital: true },
    Port { name: "Marseille", col: 36, row: 9, econ: 0, specialty: -1, capital: false },
    Port { name: "Mecca", col: 43, row: 13, econ: 5, specialty: 24, capital: false },
    Port { name: "Mombasa", col: 43, row: 18, econ: 4, specialty: 14, capital: true },
    Port { name: "Mozambique", col: 44, row: 21, econ: 4, specialty: 10, capital: false },
    Port { name: "Muscat", col: 47, row: 13, econ: 5, specialty: -1, capital: false },
    Port { name: "Nagasaki", col: 61, row: 11, econ: 7, specialty: 11, capital: true },
    Port { name: "Naples", col: 38, row: 10, econ: 0, specialty: 18, capital: false },
    Port { name: "Nova Granada", col: 20, row: 15, econ: -1, specialty: -1, capital: false },
    Port { name: "Oslo", col: 38, row: 6, econ: 1, specialty: 22, capital: false },
    Port { name: "Panama", col: 20, row: 16, econ: 2, specialty: -1, capital: false },
    Port { name: "Pernambuco", col: 29, row: 19, econ: 2, specialty: -1, capital: false },
    Port { name: "Pisa", col: 38, row: 9, econ: 0, specialty: 24, capital: false },
    Port { name: "Rio de Janeiro", col: 27, row: 22, econ: -1, specialty: -1, capital: false },
    Port { name: "Rio Grande", col: 25, row: 24, econ: -1, specialty: -1, capital: false },
    Port { name: "Ruwen", col: 43, row: 19, econ: -1, specialty: -1, capital: false },
    Port { name: "San Jorge", col: 35, row: 16, econ: 3, specialty: 14, capital: true },
    Port { name: "Santo Domingo", col: 22, row: 14, econ: 2, specialty: 13, capital: true },
    Port { name: "Seville", col: 34, row: 11, econ: 0, specialty: -1, capital: false },
    Port { name: "Siber", col: 50, row: 4, econ: -1, specialty: -1, capital: false },
    Port { name: "Sofala", col: 42, row: 22, econ: 4, specialty: 10, capital: false },
    Port { name: "Sumatra", col: 55, row: 16, econ: 6, specialty: 0, capital: false },
    Port { name: "Tanisk", col: 65, row: 6, econ: -1, specialty: -1, capital: false },
    Port { name: "Ternate", col: 61, row: 17, econ: 6, specialty: 4, capital: false },
    Port { name: "Trebizond", col: 43, row: 9, econ: 0, specialty: 16, capital: false },
    Port { name: "Tunis", col: 38, row: 11, econ: 0, specialty: -1, capital: false },
    Port { name: "Valencia", col: 35, row: 10, econ: 0, specialty: 18, capital: false },
    Port { name: "Venice", col: 38, row: 8, econ: 0, specialty: 23, capital: true },
    Port { name: "Veracruz", col: 16, row: 13, econ: 2, specialty: -1, capital: false },
    Port { name: "Verde", col: 31, row: 15, econ: -1, specialty: -1, capital: false },
    Port { name: "Virginia", col: 20, row: 10, econ: -1, specialty: -1, capital: false },
    Port { name: "Zeiton", col: 59, row: 13, econ: 7, specialty: 17, capital: false },
];

pub const ECONOMIES: [&str; 8] = [
    "Mediterranean",
    "N. Europe",
    "Americas",
    "West Africa",
    "East Africa",
    "Arabia",
    "SE Asia",
    "Far East",
];

pub const GOODS: [&str; 42] = [
    "Pepper",
    "Cinnamon",
    "Nutmeg",
    "Pimento",
    "Cloves",
    "Olive Oil",
    "Grapes",
    "Sugar",
    "Cheese",
    "Grain",
    "Gold",
    "Silver",
    "Quartz",
    "Coral",
    "Ivory",
    "Pearl",
    "Cotton",
    "Raw Silk",
    "Wool",
    "Cloth",
    "Silk",
    "Firearms",
    "Wood",
    "Porcelain",
    "Artwork",
    "Carpet",
    "Tobacco",
    "Cacao",
    "Dyewood",
    "Salt",
    "Gum Arabic",
    "Ambergris",
    "Tortoiseshell",
    "Frankincense",
    "Coffee",
    "Sandalwood",
    "Camphor",
    "Tea",
    "Jade",
    "Amber",
    "Iron",
    "Glassware",
];

/// Base price in gold to buy one unit, indexed [good][economy].
/// -1 means no port of that economy stocks it.
pub const BUY: [[i16; 8]; 42] = [
    [-1, -1, -1, -1, -1, -1, 3, -1], // Pepper
    [-1, -1, -1, -1, -1, -1, 7, -1], // Cinnamon
    [-1, -1, -1, -1, -1, -1, 6, -1], // Nutmeg
    [-1, -1, -1, -1, -1, 42, -1, -1], // Pimento
    [-1, -1, -1, -1, -1, -1, 12, -1], // Cloves
    [42, -1, -1, -1, -1, 30, -1, -1], // Olive Oil
    [38, 47, -1, -1, -1, -1, -1, -1], // Grapes
    [25, 31, -1, -1, -1, -1, -1, -1], // Sugar
    [-1, 35, -1, -1, -1, -1, -1, -1], // Cheese
    [10, 12, -1, -1, -1, 18, 10, -1], // Grain
    [-1, -1, 400, 750, 515, -1, -1, -1], // Gold
    [-1, -1, -1, -1, -1, -1, -1, 30], // Silver
    [-1, -1, -1, -1, 180, 105, -1, -1], // Quartz
    [-1, -1, 98, -1, -1, -1, -1, -1], // Coral
    [-1, -1, -1, 126, 105, -1, -1, -1], // Ivory
    [-1, -1, -1, -1, -1, -1, -1, 170], // Pearl
    [87, -1, 22, 30, 25, 20, 15, -1], // Cotton
    [-1, -1, -1, -1, -1, -1, -1, 30], // Raw Silk
    [45, 48, -1, -1, -1, 20, -1, -1], // Wool
    [60, 62, -1, -1, -1, -1, 30, -1], // Cloth
    [-1, -1, -1, -1, -1, -1, -1, 45], // Silk
    [100, 105, -1, -1, -1, -1, -1, -1], // Firearms
    [-1, 33, -1, -1, 28, -1, -1, -1], // Wood
    [60, 60, -1, -1, -1, -1, -1, 25], // Porcelain
    [280, -1, -1, -1, -1, 160, -1, 140], // Artwork
    [-1, -1, -1, -1, -1, 70, -1, -1], // Carpet
    [-1, -1, 20, -1, -1, -1, -1, -1], // Tobacco
    [-1, -1, 28, -1, -1, -1, -1, -1], // Cacao
    [-1, -1, 35, 40, -1, -1, -1, -1], // Dyewood
    [8, -1, -1, 6, -1, -1, -1, -1], // Salt
    [-1, -1, -1, 25, -1, 30, -1, -1], // Gum Arabic
    [-1, -1, -1, -1, 210, -1, -1, -1], // Ambergris
    [-1, -1, -1, -1, 55, -1, 48, -1], // Tortoiseshell
    [-1, -1, -1, -1, 45, 38, -1, -1], // Frankincense
    [-1, -1, -1, -1, -1, 22, -1, -1], // Coffee
    [-1, -1, -1, -1, 60, -1, 50, -1], // Sandalwood
    [-1, -1, -1, -1, -1, -1, 65, -1], // Camphor
    [-1, -1, -1, -1, -1, -1, -1, 35], // Tea
    [-1, -1, -1, -1, -1, -1, -1, 120], // Jade
    [-1, 95, -1, -1, -1, -1, -1, -1], // Amber
    [55, 40, -1, -1, -1, -1, -1, -1], // Iron
    [85, -1, -1, -1, -1, -1, -1, -1], // Glassware
];

/// Base price in gold to sell one unit, indexed [good][economy].
/// -1 means every port of that economy already sells it, so there is no
/// market: carrying pepper to a pepper coast is the mistake the game is
/// about. The simulation prices those at a fraction of the buy price.
pub const SELL: [[i16; 8]; 42] = [
    [80, 110, 64, 52, 35, 42, 2, 20], // Pepper
    [70, 80, 40, 32, 43, 30, 3, 20], // Cinnamon
    [100, 105, 32, 30, 28, 28, 3, 20], // Nutmeg
    [110, 120, 25, 35, 30, 15, 4, 30], // Pimento
    [105, 108, 30, 42, 29, 30, 4, 20], // Cloves
    [-1, 55, 58, 60, 38, -1, 10, 2], // Olive Oil
    [-1, 62, 25, 30, 30, 20, 15, 40], // Grapes
    [45, 49, 48, 50, 50, 50, 45, 42], // Sugar
    [40, -1, 50, 45, 40, 58, 62, 50], // Cheese
    [20, -1, 40, 35, 42, -1, -1, 5], // Grain
    [1000, 1000, -1, -1, 300, 890, 1050, 900], // Gold
    [120, 120, 100, 80, 280, 380, 110, 200], // Silver
    [320, 325, 230, 220, -1, 300, 330, 320], // Quartz
    [280, 275, 270, 290, 260, 350, 105, 120], // Coral
    [300, 350, 220, 200, 195, 290, 120, 140], // Ivory
    [220, 220, 175, 170, 160, 230, 120, -1], // Pearl
    [80, 110, -1, -1, -1, -1, -1, 42], // Cotton
    [120, 130, 50, 40, 40, 80, 85, 90], // Raw Silk
    [65, 55, 21, 12, 16, -1, 16, 10], // Wool
    [-1, -1, 80, 84, 89, 85, 16, 92], // Cloth
    [140, 150, 50, 45, 48, 50, 70, -1], // Silk
    [-1, -1, 170, 140, 190, 230, 205, 240], // Firearms
    [60, 58, 18, 35, -1, 60, 10, 15], // Wood
    [105, -1, 45, 40, 35, 40, 35, -1], // Porcelain
    [400, 400, 300, 30, 45, 150, 160, -1], // Artwork
    [320, 340, 115, 140, 120, -1, 75, 50], // Carpet
    [95, 120, -1, 55, 50, 60, 45, 55], // Tobacco
    [130, 145, -1, 60, 55, 70, 50, 60], // Cacao
    [150, 165, -1, -1, 70, 90, 60, 75], // Dyewood
    [-1, 22, 30, -1, 28, 20, 25, 18], // Salt
    [90, 100, 40, -1, 45, -1, 40, 50], // Gum Arabic
    [600, 640, 300, 260, -1, 520, 330, 480], // Ambergris
    [190, 205, 90, 80, -1, 150, -1, 175], // Tortoiseshell
    [160, 175, 70, 60, -1, -1, 80, 130], // Frankincense
    [115, 135, 55, 48, 50, -1, 60, 70], // Coffee
    [175, 185, 75, 65, -1, 140, -1, 200], // Sandalwood
    [210, 225, 85, 70, 90, 160, -1, 230], // Camphor
    [155, 180, 70, 55, 60, 95, 65, -1], // Tea
    [380, 395, 150, 120, 130, 300, 260, -1], // Jade
    [290, -1, 130, 110, 120, 330, 250, 310], // Amber
    [-1, -1, 120, 130, 125, 110, 115, 95], // Iron
    [-1, 130, 190, 210, 200, 165, 180, 145], // Glassware
];

/// Landmasses rasterised into LAND, for the record: 28.
pub const LANDMASSES: [&str; 28] = [
    "Africa",
    "Eurasia",
    "Britain",
    "Ireland",
    "Iceland",
    "Scandinavia_Baltic",
    "Japan",
    "Madagascar",
    "Sri_Lanka",
    "North_America",
    "Greenland",
    "South_America",
    "Cuba",
    "Hispaniola",
    "Australia",
    "New_Guinea",
    "Sumatra_Java",
    "Borneo",
    "Sulawesi",
    "Philippines",
    "Antarctica",
    "-Black_Sea",
    "-Red_Sea",
    "-Persian_Gulf",
    "-Sea_of_Okhotsk",
    "Mariana_Islands",
    "Hawaii",
    "Cape_Verde",
];
